version: "3.8"

services:
  madokami:
    image: "summerkirakira/madokami:latest"
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/backend/data


  aria2:
    image: p3terx/aria2-pro
    restart: always
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    environment:
      - RPC_SECRET=MADOKAMI
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - UMASK_SET=022
      - PUID=65534
      - PGID=65534
    volumes:
      - ./data/aria2/downloads:/downloads
      - ./data/aria2/config:/config

  ariang:
      container_name: ariang
      image: p3terx/ariang
      command: --port 6880 --ipv6
      network_mode: bridge
      ports:
        - 6880:6880
      restart: unless-stopped
      logging:
        driver: json-file
        options:
          max-size: 1m