/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    episode: number;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    path: string;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    addTime: number;
}

/**
 * Check if a given object implements the Content interface.
 */
export function instanceOfContent(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('episode' in value)) return false;
    if (!('link' in value)) return false;
    if (!('path' in value)) return false;
    if (!('addTime' in value)) return false;
    return true;
}

export function ContentFromJSON(json: any): Content {
    return ContentFromJSONTyped(json, false);
}

export function ContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Content {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'episode': json['episode'],
        'link': json['link'],
        'path': json['path'],
        'addTime': json['add_time'],
    };
}

export function ContentToJSON(value?: Content | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'episode': value['episode'],
        'link': value['link'],
        'path': value['path'],
        'add_time': value['addTime'],
    };
}

