/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadData
 */
export interface DownloadData {
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof DownloadData
     */
    isMetadata: boolean;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    targetPath: string;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    dir: string;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    totalLength: number;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    progress: number;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    currentDownload: number;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    currentSpeed: number;
}

/**
 * Check if a given object implements the DownloadData interface.
 */
export function instanceOfDownloadData(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('isMetadata' in value)) return false;
    if (!('name' in value)) return false;
    if (!('targetPath' in value)) return false;
    if (!('dir' in value)) return false;
    if (!('totalLength' in value)) return false;
    if (!('progress' in value)) return false;
    if (!('currentDownload' in value)) return false;
    if (!('status' in value)) return false;
    if (!('currentSpeed' in value)) return false;
    return true;
}

export function DownloadDataFromJSON(json: any): DownloadData {
    return DownloadDataFromJSONTyped(json, false);
}

export function DownloadDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'isMetadata': json['is_metadata'],
        'name': json['name'],
        'targetPath': json['target_path'],
        'dir': json['dir'],
        'totalLength': json['total_length'],
        'progress': json['progress'],
        'currentDownload': json['current_download'],
        'status': json['status'],
        'currentSpeed': json['current_speed'],
    };
}

export function DownloadDataToJSON(value?: DownloadData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'is_metadata': value['isMetadata'],
        'name': value['name'],
        'target_path': value['targetPath'],
        'dir': value['dir'],
        'total_length': value['totalLength'],
        'progress': value['progress'],
        'current_download': value['currentDownload'],
        'status': value['status'],
        'current_speed': value['currentSpeed'],
    };
}

