/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DownloadData } from './DownloadData';
import {
    DownloadDataFromJSON,
    DownloadDataFromJSONTyped,
    DownloadDataToJSON,
} from './DownloadData';

/**
 * 
 * @export
 * @interface DownloadResponse
 */
export interface DownloadResponse {
    /**
     * 
     * @type {string}
     * @memberof DownloadResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DownloadResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DownloadResponse
     */
    title?: string;
    /**
     * 
     * @type {Array<DownloadData>}
     * @memberof DownloadResponse
     */
    data?: Array<DownloadData>;
}

/**
 * Check if a given object implements the DownloadResponse interface.
 */
export function instanceOfDownloadResponse(value: object): boolean {
    return true;
}

export function DownloadResponseFromJSON(json: any): DownloadResponse {
    return DownloadResponseFromJSONTyped(json, false);
}

export function DownloadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'title': json['title'] == null ? undefined : json['title'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DownloadDataFromJSON)),
    };
}

export function DownloadResponseToJSON(value?: DownloadResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'success': value['success'],
        'title': value['title'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DownloadDataToJSON)),
    };
}

