/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfoMessage
 */
export interface InfoMessage {
    /**
     * 
     * @type {string}
     * @memberof InfoMessage
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InfoMessage
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InfoMessage
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InfoMessage
     */
    data?: string;
}

/**
 * Check if a given object implements the InfoMessage interface.
 */
export function instanceOfInfoMessage(value: object): boolean {
    return true;
}

export function InfoMessageFromJSON(json: any): InfoMessage {
    return InfoMessageFromJSONTyped(json, false);
}

export function InfoMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'title': json['title'] == null ? undefined : json['title'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function InfoMessageToJSON(value?: InfoMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'success': value['success'],
        'title': value['title'],
        'data': value['data'],
    };
}

