/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
} from './Media';

/**
 * 
 * @export
 * @interface MediasResponse
 */
export interface MediasResponse {
    /**
     * 
     * @type {string}
     * @memberof MediasResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediasResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediasResponse
     */
    title?: string;
    /**
     * 
     * @type {Array<Media>}
     * @memberof MediasResponse
     */
    data?: Array<Media>;
}

/**
 * Check if a given object implements the MediasResponse interface.
 */
export function instanceOfMediasResponse(value: object): boolean {
    return true;
}

export function MediasResponseFromJSON(json: any): MediasResponse {
    return MediasResponseFromJSONTyped(json, false);
}

export function MediasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediasResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'title': json['title'] == null ? undefined : json['title'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MediaFromJSON)),
    };
}

export function MediasResponseToJSON(value?: MediasResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'success': value['success'],
        'title': value['title'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MediaToJSON)),
    };
}

