/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
} from './Media';

/**
 * 
 * @export
 * @interface MediaResponse
 */
export interface MediaResponse {
    /**
     * 
     * @type {string}
     * @memberof MediaResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediaResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediaResponse
     */
    title?: string;
    /**
     * 
     * @type {Media}
     * @memberof MediaResponse
     */
    data?: Media;
}

/**
 * Check if a given object implements the MediaResponse interface.
 */
export function instanceOfMediaResponse(value: object): boolean {
    return true;
}

export function MediaResponseFromJSON(json: any): MediaResponse {
    return MediaResponseFromJSONTyped(json, false);
}

export function MediaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'title': json['title'] == null ? undefined : json['title'],
        'data': json['data'] == null ? undefined : MediaFromJSON(json['data']),
    };
}

export function MediaResponseToJSON(value?: MediaResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'success': value['success'],
        'title': value['title'],
        'data': MediaToJSON(value['data']),
    };
}

