/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    'episode': number;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'link': string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'path': string;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    'add_time': number;
}
/**
 * 
 * @export
 * @interface DownloadData
 */
export interface DownloadData {
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof DownloadData
     */
    'is_metadata': boolean;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    'target_path': string;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    'dir': string;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    'total_length': number;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    'progress': number;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    'current_download': number;
    /**
     * 
     * @type {string}
     * @memberof DownloadData
     */
    'status': string;
    /**
     * 
     * @type {number}
     * @memberof DownloadData
     */
    'current_speed': number;
}
/**
 * 
 * @export
 * @interface DownloadItem
 */
export interface DownloadItem {
    /**
     * 
     * @type {string}
     * @memberof DownloadItem
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DownloadItem
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DownloadItem
     */
    'title'?: string;
    /**
     * 
     * @type {DownloadData}
     * @memberof DownloadItem
     */
    'data'?: DownloadData | null;
}
/**
 * 
 * @export
 * @interface DownloadResponse
 */
export interface DownloadResponse {
    /**
     * 
     * @type {string}
     * @memberof DownloadResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DownloadResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DownloadResponse
     */
    'title'?: string;
    /**
     * 
     * @type {Array<DownloadData>}
     * @memberof DownloadResponse
     */
    'data'?: Array<DownloadData> | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface InfoMessage
 */
export interface InfoMessage {
    /**
     * 
     * @type {string}
     * @memberof InfoMessage
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InfoMessage
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InfoMessage
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof InfoMessage
     */
    'data'?: string;
}
/**
 * 
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * 
     * @type {Array<Content>}
     * @memberof Media
     */
    'contents': Array<Content>;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    'link': string;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof Media
     */
    'bangumi_id': number | null;
    /**
     * 
     * @type {number}
     * @memberof Media
     */
    'season': number;
}
/**
 * 
 * @export
 * @interface MediaResponse
 */
export interface MediaResponse {
    /**
     * 
     * @type {string}
     * @memberof MediaResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediaResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediaResponse
     */
    'title'?: string;
    /**
     * 
     * @type {Media}
     * @memberof MediaResponse
     */
    'data'?: Media | null;
}
/**
 * 
 * @export
 * @interface MediasResponse
 */
export interface MediasResponse {
    /**
     * 
     * @type {string}
     * @memberof MediasResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediasResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediasResponse
     */
    'title'?: string;
    /**
     * 
     * @type {Array<Media>}
     * @memberof MediasResponse
     */
    'data'?: Array<Media> | null;
}
/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'username': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    'is_superuser': boolean;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DownloadApi - axios parameter creator
 * @export
 */
export const DownloadApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDownloadV1DownloadDownloadIdGet: async (downloadId: string, xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'downloadId' is not null or undefined
            assertParamExists('getDownloadV1DownloadDownloadIdGet', 'downloadId', downloadId)
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('getDownloadV1DownloadDownloadIdGet', 'xToken', xToken)
            const localVarPath = `/v1/download/{download_id}`
                .replace(`{${"download_id"}}`, encodeURIComponent(String(downloadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Downloads
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDownloadsV1DownloadAllGet: async (xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('getDownloadsV1DownloadAllGet', 'xToken', xToken)
            const localVarPath = `/v1/download/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Pause Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseDownloadV1DownloadPauseDownloadIdGet: async (downloadId: string, xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'downloadId' is not null or undefined
            assertParamExists('pauseDownloadV1DownloadPauseDownloadIdGet', 'downloadId', downloadId)
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('pauseDownloadV1DownloadPauseDownloadIdGet', 'xToken', xToken)
            const localVarPath = `/v1/download/pause/{download_id}`
                .replace(`{${"download_id"}}`, encodeURIComponent(String(downloadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeDownloadV1DownloadRemoveDownloadIdGet: async (downloadId: string, xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'downloadId' is not null or undefined
            assertParamExists('removeDownloadV1DownloadRemoveDownloadIdGet', 'downloadId', downloadId)
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('removeDownloadV1DownloadRemoveDownloadIdGet', 'xToken', xToken)
            const localVarPath = `/v1/download/remove/{download_id}`
                .replace(`{${"download_id"}}`, encodeURIComponent(String(downloadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resume Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeDownloadV1DownloadResumeDownloadIdGet: async (downloadId: string, xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'downloadId' is not null or undefined
            assertParamExists('resumeDownloadV1DownloadResumeDownloadIdGet', 'downloadId', downloadId)
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('resumeDownloadV1DownloadResumeDownloadIdGet', 'xToken', xToken)
            const localVarPath = `/v1/download/resume/{download_id}`
                .replace(`{${"download_id"}}`, encodeURIComponent(String(downloadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadApi - functional programming interface
 * @export
 */
export const DownloadApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DownloadApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDownloadV1DownloadDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDownloadV1DownloadDownloadIdGet(downloadId, xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DownloadApi.getDownloadV1DownloadDownloadIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Downloads
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDownloadsV1DownloadAllGet(xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDownloadsV1DownloadAllGet(xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DownloadApi.getDownloadsV1DownloadAllGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Pause Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pauseDownloadV1DownloadPauseDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pauseDownloadV1DownloadPauseDownloadIdGet(downloadId, xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DownloadApi.pauseDownloadV1DownloadPauseDownloadIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeDownloadV1DownloadRemoveDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeDownloadV1DownloadRemoveDownloadIdGet(downloadId, xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DownloadApi.removeDownloadV1DownloadRemoveDownloadIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Resume Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resumeDownloadV1DownloadResumeDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resumeDownloadV1DownloadResumeDownloadIdGet(downloadId, xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DownloadApi.resumeDownloadV1DownloadResumeDownloadIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DownloadApi - factory interface
 * @export
 */
export const DownloadApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DownloadApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDownloadV1DownloadDownloadIdGet(downloadId: string, xToken: string, options?: any): AxiosPromise<DownloadItem> {
            return localVarFp.getDownloadV1DownloadDownloadIdGet(downloadId, xToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Downloads
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDownloadsV1DownloadAllGet(xToken: string, options?: any): AxiosPromise<DownloadResponse> {
            return localVarFp.getDownloadsV1DownloadAllGet(xToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Pause Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseDownloadV1DownloadPauseDownloadIdGet(downloadId: string, xToken: string, options?: any): AxiosPromise<DownloadItem> {
            return localVarFp.pauseDownloadV1DownloadPauseDownloadIdGet(downloadId, xToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeDownloadV1DownloadRemoveDownloadIdGet(downloadId: string, xToken: string, options?: any): AxiosPromise<DownloadItem> {
            return localVarFp.removeDownloadV1DownloadRemoveDownloadIdGet(downloadId, xToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resume Download
         * @param {string} downloadId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeDownloadV1DownloadResumeDownloadIdGet(downloadId: string, xToken: string, options?: any): AxiosPromise<DownloadItem> {
            return localVarFp.resumeDownloadV1DownloadResumeDownloadIdGet(downloadId, xToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DownloadApi - object-oriented interface
 * @export
 * @class DownloadApi
 * @extends {BaseAPI}
 */
export class DownloadApi extends BaseAPI {
    /**
     * 
     * @summary Get Download
     * @param {string} downloadId 
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadApi
     */
    public getDownloadV1DownloadDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig) {
        return DownloadApiFp(this.configuration).getDownloadV1DownloadDownloadIdGet(downloadId, xToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Downloads
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadApi
     */
    public getDownloadsV1DownloadAllGet(xToken: string, options?: RawAxiosRequestConfig) {
        return DownloadApiFp(this.configuration).getDownloadsV1DownloadAllGet(xToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Pause Download
     * @param {string} downloadId 
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadApi
     */
    public pauseDownloadV1DownloadPauseDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig) {
        return DownloadApiFp(this.configuration).pauseDownloadV1DownloadPauseDownloadIdGet(downloadId, xToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove Download
     * @param {string} downloadId 
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadApi
     */
    public removeDownloadV1DownloadRemoveDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig) {
        return DownloadApiFp(this.configuration).removeDownloadV1DownloadRemoveDownloadIdGet(downloadId, xToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resume Download
     * @param {string} downloadId 
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadApi
     */
    public resumeDownloadV1DownloadResumeDownloadIdGet(downloadId: string, xToken: string, options?: RawAxiosRequestConfig) {
        return DownloadApiFp(this.configuration).resumeDownloadV1DownloadResumeDownloadIdGet(downloadId, xToken, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EngineApi - axios parameter creator
 * @export
 */
export const EngineApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Run Engine
         * @param {string} engineNamespace 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runEngineV1EngineRunGet: async (engineNamespace: string, xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'engineNamespace' is not null or undefined
            assertParamExists('runEngineV1EngineRunGet', 'engineNamespace', engineNamespace)
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('runEngineV1EngineRunGet', 'xToken', xToken)
            const localVarPath = `/v1/engine/run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (engineNamespace !== undefined) {
                localVarQueryParameter['engine_namespace'] = engineNamespace;
            }

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EngineApi - functional programming interface
 * @export
 */
export const EngineApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EngineApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Run Engine
         * @param {string} engineNamespace 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runEngineV1EngineRunGet(engineNamespace: string, xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InfoMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runEngineV1EngineRunGet(engineNamespace, xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EngineApi.runEngineV1EngineRunGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EngineApi - factory interface
 * @export
 */
export const EngineApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EngineApiFp(configuration)
    return {
        /**
         * 
         * @summary Run Engine
         * @param {string} engineNamespace 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runEngineV1EngineRunGet(engineNamespace: string, xToken: string, options?: any): AxiosPromise<InfoMessage> {
            return localVarFp.runEngineV1EngineRunGet(engineNamespace, xToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EngineApi - object-oriented interface
 * @export
 * @class EngineApi
 * @extends {BaseAPI}
 */
export class EngineApi extends BaseAPI {
    /**
     * 
     * @summary Run Engine
     * @param {string} engineNamespace 
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EngineApi
     */
    public runEngineV1EngineRunGet(engineNamespace: string, xToken: string, options?: RawAxiosRequestConfig) {
        return EngineApiFp(this.configuration).runEngineV1EngineRunGet(engineNamespace, xToken, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MediaApi - axios parameter creator
 * @export
 */
export const MediaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary  Get All Media
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMediaV1MediaAllGet: async (xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('getAllMediaV1MediaAllGet', 'xToken', xToken)
            const localVarPath = `/v1/media/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary  Get Cover Image
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoverImageV1MediaCoverMediaIdGet: async (mediaId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('getCoverImageV1MediaCoverMediaIdGet', 'mediaId', mediaId)
            const localVarPath = `/v1/media/cover/{media_id}`
                .replace(`{${"media_id"}}`, encodeURIComponent(String(mediaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary  Get Media
         * @param {string} mediaId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMediaV1MediaMediaIdGet: async (mediaId: string, xToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('getMediaV1MediaMediaIdGet', 'mediaId', mediaId)
            // verify required parameter 'xToken' is not null or undefined
            assertParamExists('getMediaV1MediaMediaIdGet', 'xToken', xToken)
            const localVarPath = `/v1/media/{media_id}`
                .replace(`{${"media_id"}}`, encodeURIComponent(String(mediaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xToken != null) {
                localVarHeaderParameter['x-token'] = String(xToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MediaApi - functional programming interface
 * @export
 */
export const MediaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MediaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary  Get All Media
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMediaV1MediaAllGet(xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MediasResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMediaV1MediaAllGet(xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MediaApi.getAllMediaV1MediaAllGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary  Get Cover Image
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoverImageV1MediaCoverMediaIdGet(mediaId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCoverImageV1MediaCoverMediaIdGet(mediaId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MediaApi.getCoverImageV1MediaCoverMediaIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary  Get Media
         * @param {string} mediaId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMediaV1MediaMediaIdGet(mediaId: string, xToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MediaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMediaV1MediaMediaIdGet(mediaId, xToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MediaApi.getMediaV1MediaMediaIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MediaApi - factory interface
 * @export
 */
export const MediaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MediaApiFp(configuration)
    return {
        /**
         * 
         * @summary  Get All Media
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMediaV1MediaAllGet(xToken: string, options?: any): AxiosPromise<MediasResponse> {
            return localVarFp.getAllMediaV1MediaAllGet(xToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary  Get Cover Image
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoverImageV1MediaCoverMediaIdGet(mediaId: string, options?: any): AxiosPromise<any> {
            return localVarFp.getCoverImageV1MediaCoverMediaIdGet(mediaId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary  Get Media
         * @param {string} mediaId 
         * @param {string} xToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMediaV1MediaMediaIdGet(mediaId: string, xToken: string, options?: any): AxiosPromise<MediaResponse> {
            return localVarFp.getMediaV1MediaMediaIdGet(mediaId, xToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MediaApi - object-oriented interface
 * @export
 * @class MediaApi
 * @extends {BaseAPI}
 */
export class MediaApi extends BaseAPI {
    /**
     * 
     * @summary  Get All Media
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public getAllMediaV1MediaAllGet(xToken: string, options?: RawAxiosRequestConfig) {
        return MediaApiFp(this.configuration).getAllMediaV1MediaAllGet(xToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary  Get Cover Image
     * @param {string} mediaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public getCoverImageV1MediaCoverMediaIdGet(mediaId: string, options?: RawAxiosRequestConfig) {
        return MediaApiFp(this.configuration).getCoverImageV1MediaCoverMediaIdGet(mediaId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary  Get Media
     * @param {string} mediaId 
     * @param {string} xToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public getMediaV1MediaMediaIdGet(mediaId: string, xToken: string, options?: RawAxiosRequestConfig) {
        return MediaApiFp(this.configuration).getMediaV1MediaMediaIdGet(mediaId, xToken, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary  Create User
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserV1UserCreatePost: async (userCreate: UserCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreate' is not null or undefined
            assertParamExists('createUserV1UserCreatePost', 'userCreate', userCreate)
            const localVarPath = `/v1/user/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary  Get Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersV1UserAllGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/user/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary  User Login
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userLoginV1userLoginPost: async (userCreate: UserCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreate' is not null or undefined
            assertParamExists('userLoginV1userLoginPost', 'userCreate', userCreate)
            const localVarPath = `/v1user/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary  Create User
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserV1UserCreatePost(userCreate: UserCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InfoMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserV1UserCreatePost(userCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.createUserV1UserCreatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary  Get Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsersV1UserAllGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsersV1UserAllGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUsersV1UserAllGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary  User Login
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userLoginV1userLoginPost(userCreate: UserCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InfoMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userLoginV1userLoginPost(userCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userLoginV1userLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary  Create User
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserV1UserCreatePost(userCreate: UserCreate, options?: any): AxiosPromise<InfoMessage> {
            return localVarFp.createUserV1UserCreatePost(userCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary  Get Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersV1UserAllGet(options?: any): AxiosPromise<Array<UserResponse>> {
            return localVarFp.getUsersV1UserAllGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary  User Login
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userLoginV1userLoginPost(userCreate: UserCreate, options?: any): AxiosPromise<InfoMessage> {
            return localVarFp.userLoginV1userLoginPost(userCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary  Create User
     * @param {UserCreate} userCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public createUserV1UserCreatePost(userCreate: UserCreate, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).createUserV1UserCreatePost(userCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary  Get Users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUsersV1UserAllGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUsersV1UserAllGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary  User Login
     * @param {UserCreate} userCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userLoginV1userLoginPost(userCreate: UserCreate, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userLoginV1userLoginPost(userCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



