name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
    - name: Install toml-cli
      run: pip install toml

    - name: Get version from pyproject.toml
      id: get_version
      run: echo "VERSION=$(python backend/read_version.py)" >> $GITHUB_ENV
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERACC }}
        password: ${{ secrets.DOCKERPWD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.4.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY }}:latest, ${{ secrets.REGISTRY }}:${{ env.VERSION }}
        
